language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - php vendor/bin/phpcs --standard=psr2 src/
  - php vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v
